language: python
python:
  #- "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
matrix:
  exclude:
    - python: "2.7"
  include:
    - python: "2.7"
      env:
        - COVERAGE=true
        - DOCS=true
        - DEPLOY_DOCS=true
    - python: "3.4"
      env: DOCS=true

before_install:
  - chmod +x ./.scripts/run_tests.sh
  - chmod +x ./.scripts/deploy_docs.sh
install:
  - pip install tox
script:
  - ./.scripts/run_tests.sh
  - if [ ! -z "$DOCS" ]; then tox -e docs; fi
  - if [ ! -z "$DEPLOY_DOCS" ]; then ./.scripts/deploy_docs.sh; fi
  - if [ ! -z "$COVERAGE" ]; then tox -e coverage; fi